<script type="text/javascript">
    $(function() {
        $('#open').click(function() {
			$('#dialog').dialog('open');
		})
		.hover(
			function(){
				$(this).addClass("ui-state-hover");
			},
			function(){
				$(this).removeClass("ui-state-hover");
			}
		).mousedown(function(){
			$(this).addClass("ui-state-active");
		})
		.mouseup(function(){
				$(this).removeClass("ui-state-active");
		});

    });
</script>

<style type="text/css">
    
    #login input { width:200px;  }
    #login #submitbutton { width: 80px; }
    #login dd { text-align: center; }
    
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework and jQuery!</span></h1>

    
<h3>Date picker</h3>

Pick your Date: <?php echo $this->datePicker("dp1",
                            '',
                        array('defaultDate' => date('Y/m/d', time()))); ?>
</div>

<h3>Form dialog</h3>

<div>
Open <a id="open" href="#">dialog</a>
</div>

<h3>Tab</h3>

<?php

$this->tabPane("newstab",
                  "text",
                  array('title' => "title"));

echo $this->tabContainer("newstab",
                        array('ddd'),
                        array('class' => 'flora')); 

/**
$content = "<form id='login' method='post' action='".$this->url(array("controller"=>"index", "action"=>"auth"))."'>";
$content .= "<div><label for='login'>Login</label><input name='login' /></div>";
$content .= "<div><label for='pass'>Password</label><input name='pass' type='password' /></div>";
$content .= "<div class='center'><button type='submit'>Login</button></div>";
$content .= "</form>";
*/

$content = $this->form;
                        
echo $this->dialogContainer("dialog", $content, array('title' => 'Login','bigiframe' => true, 'modal' => true,  'resizable'=> false, 'autoOpen' =>false), array());
?>