<?php

 $this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui-1.7.2.redmond.css',"screen,projection");
?>

<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>

<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>

Pick your Date: <?php echo $this->datePicker("dp1",
                            '',
                        array('defaultDate' => date('Y/m/d', time()))); ?>

</div>
