<script>
$(document).ready(dialogForms);

function dialogForms() {
  $('a.dialog-form').click(function() {
    var a = $(this);
    $.get(a.attr('href'),function(resp){
      var dialog = $('<div>').attr('id','formDialog').html($(resp).find('form:first').parent('div').html());
      $('body').append(dialog);
      dialog.find(':submit').hide();
      dialog.dialog({
        title: a.attr('title') ? a.attr('title') : '',
        modal: true,
        buttons: {
          'Save': function() {submitFormWithAjax($(this).find('form'));},
          'Cancel': function() {$(this).dialog('close');}
        },
        close: function() {$(this).remove();},
        width: 'auto'
      });
    }, 'html');
    return false;
  });
}

function submitFormWithAjax(form) {
  form = $(form);
  $.ajax({
    url: form.attr('action'),
    data: form.serialize(),
    type: (form.attr('method')),
    dataType: 'script'
  });

   $('#formDialog').dialog('close');

  $.ajax({
    url:  '<?php echo $this->url(array("controller"=>"modal","action"=>"update")); ?>',
    type: "POST",
    dataType: "html",
    success: function(html) {
        $('#items').replaceWith(html);
    }
  });


  
}

 </script>
<a href="<?php echo $this->url(array("controller"=>"modal","action"=>"new")); ?>" class="dialog-form" title="Add New Item">New Item</a>

<?php echo $this->form; ?>