<?php echo $this->docType() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink()->toString(); ?>
    
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.3.2.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-ui-1.7.2.custom.min.js"></script>

        <!--
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/menu.js" </script>
        -->
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/jquery-ui-1.7.2.custom.css'); ?>


</head>
<body>

<div id="wrap">

	<div id="content">
                <?php echo $this->layout()->content; ?>
	</div>


</div>
</body>
</html>
