<?php echo $this->docType() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink()->toString(); ?>
    <script type="text/javascript"
            src="http://www.google.com/jsapi"></script>
    <script type="text/javascript">
            google.load("jquery", "1.3.2");
            google.load("jqueryui", "1.7.2");
    </script>
   <?php echo $this->jQuery()->addStylesheet($this->baseUrl() . '/css/jquery-ui-1.7.2.custom.css'); ?>

</head>
<body>

<div id="wrap">

	<div id="content">
                <?php echo $this->layout()->content; ?>
	</div>


</div>
</body>
</html>
